---
  - name: Include vars of debian
    include_vars:
      file: /home/sajjad/andible/ans-proj/vars/debian.yaml

  - name: update apt cache and update system
    apt:
      update_cache: yes
      upgrade: full
    tags:
      - all
      - install

  - name: install prerequired packages
    apt:
      name: "{{item}}"
      state: present
    loop:
      - "{{packages_to_install}}" 
    tags:
      - all
      - install

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
    tags:
      - all
      - install
      - add
      
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    tags:
      - all
      - install
          
  - name: install docker packages
    apt:
      name: "{{item}}"
      update_cache: yes
      state: present
    loop:
      - "{{docker_package_to_install}}"
    tags: 
      - all
      - install


  - name: get docker version
    shell: "docker -v | cut -d ' ' -f 3 | cut -d ',' -f 1"
    ignore_errors: yes
    register: version

  - debug: 
      msg: "{{version.stdout}}"

