---
  - name: install docker on redhat-based servers
    import_tasks: redhat.yaml
    when: ansible_facts.os_family | lower == "redhat"
  
  - name: install docker on debian-based servers
    import_tasks: debian.yaml
    when: ansible_facts.os_family | lower == "debian"
